name: sic-express

on:
  workflow_dispatch:
  #schedule:
   # - cron: '0,15,30,45 7-16 * * 2-6'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4.1.1
        
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache dependency libraries
        uses: actions/cache@v4
        id: cache-libraries
        with:
          path: ${{ env.pythonLocation }}/lib/python3.10/site-packages
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

      - name: Install pip and dependencies
        if: steps.cache-libraries.outputs.cache-hit != 'true' 
        run: |
          python -m pip install -r requirements.txt

      - name: execute python script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python sic_scraper.py
